// vueapp/src/components/PdfReader.vue
<template>
  <div class="reader">
    <!-- 工具栏（手机端隐藏，改用页脚页码 + 双指缩放）-->
    <div class="reader-toolbar">
      <button class="btn btn-back" @click="close">← 返回</button>
      <span class="doc-title">{{ bookName }}</span>
      <div class="spacer"/>
      <span class="pageinfo">{{ currentPage + 1 }} / {{ total }}</span>
      <button class="btn" @click="zoomOut">－</button>
      <span class="zoom">{{ zoomLabel }}</span>
      <button class="btn" @click="zoomIn">＋</button>
    </div>

    <!-- 视口 -->
    <div class="image-viewport" ref="viewportRef" @scroll.passive="handleScroll">
      <!-- 内容轨道：宽度取最宽页面，放大后可左右拖动查看全部内容，缩小时居中 -->
      <div class="pages-track">
        <div
            v-for="page in pages"
            :key="page.pageNum"
            class="image-page"
            :data-page-num="page.pageNum"
            :style="{
              width: page.displayWidth + 'px',
              height: page.displayHeight + 'px',
            }"
        >
          <!-- canvas：pdf.js 矢量渲染，只有进入可视范围才真正下载切片并渲染 -->
          <canvas
              v-show="page.rendered"
              :ref="el => setCanvasRef(page.pageNum, el)"
              class="page-canvas"
          />
          <!-- 占位/加载/失败 -->
          <div v-if="!page.rendered && !page.error" class="ph-overlay">
            <div class="ph-icon">
              <svg viewBox="0 0 24 24" fill="none">
                <path d="M6 2h8l4 4v16H6z" stroke="currentColor" stroke-width="1.3" stroke-linejoin="round"/>
                <path d="M14 2v4h4" stroke="currentColor" stroke-width="1.3" stroke-linejoin="round"/>
              </svg>
            </div>
            <div class="ph-text">
              {{ page.loading ? `加载中 ${page.pageNum + 1}...` : `第 ${page.pageNum + 1} 页` }}
            </div>
          </div>
          <div v-if="page.error" class="err-overlay" @click="retryPage(page.pageNum)">
            <div>加载失败，点击重试</div>
          </div>
        </div>
      </div>
    </div>

    <!-- 页脚页码标记（手机端顶部工具栏隐藏时的页码提示）-->
    <div class="page-footer">{{ currentPage + 1 }} / {{ total }}</div>
  </div>
</template>

<script setup lang="ts">
import {ref, onMounted, onUnmounted, computed, reactive, nextTick} from 'vue'
import {useRoute, useRouter} from 'vue-router'
import {request, download} from '@/utils/request'
import {debounce} from '@/utils/UIUtils'
import * as pdfjsLib from 'pdfjs-dist'
// @ts-ignore vite worker 导入
import PdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?worker'

// pdf.js worker：用 Vite 的 ?worker 方式打包，随应用发布，不依赖外网 CDN
pdfjsLib.GlobalWorkerOptions.workerPort = new PdfWorker()

const route = useRoute()
const router = useRouter()
const viewportRef = ref<HTMLElement>()

// ============ 基础状态 ============
const bookId = ref<string>('')
const bookName = ref('')
const total = ref(0)
const currentPage = ref(0)
// 进度恢复用：起始页 + 页内比例(0~1)，与设备/缩放无关
const startFrac = ref(0)

// ============ 缩放 ============
// scale 为连续值，按钮走档位、双指走连续缩放
const MIN_SCALE = 0.5
const MAX_SCALE = 3
const zoomLevels = [0.5, 0.75, 1, 1.25, 1.5, 2, 3]
const scale = ref(1)
const zoomLabel = computed(() => `${Math.round(scale.value * 100)}%`)

// ============ 常量配置 ============
const MAX_CONCURRENT = 3     // 最大并发加载数
const PRELOAD_AHEAD = 2      // 向下预加载页数
const PRELOAD_BEHIND = 1     // 向上预加载页数
const OBSERVER_ROOT_MARGIN = '400px 0px' // 提前触发加载的缓冲距离
const DEFAULT_PAGE_WIDTH = 595   // A4 默认宽（pt）
const DEFAULT_PAGE_HEIGHT = 842  // A4 默认高（pt）
const VIEWPORT_WIDTH_LIMIT = 900 // 页面显示的最大宽度（保持阅读舒适）
// canvas 渲染上限，避免高分屏 devicePixelRatio 过大导致内存暴涨
const MAX_DPR = 2

// ============ 页面数据 ============
interface PageItem {
  pageNum: number
  // 原始 pt 尺寸（来自 meta）
  origWidth: number
  origHeight: number
  // 当前显示尺寸（受 scale 影响，CSS 像素）
  displayWidth: number
  displayHeight: number
  loading: boolean   // 正在下载/渲染
  rendered: boolean  // 已渲染到 canvas
  error: boolean
}

const pages = reactive<PageItem[]>([])

// canvas 元素引用（pageNum -> HTMLCanvasElement）
const canvasEls = new Map<number, HTMLCanvasElement>()
// 每页缓存的 pdf.js 文档代理（用于缩放时按新 viewport 重绘，不必重新下载）
const pageDocs = new Map<number, any>()
// 每页对应的 AbortController（用于取消下载）
const pageAborts = new Map<number, AbortController>()

function setCanvasRef(pageNum: number, el: any) {
  if (el) canvasEls.set(pageNum, el as HTMLCanvasElement)
  else canvasEls.delete(pageNum)
}

// ============ 并发调度器（下载切片 + pdf.js 渲染）============
class PageLoader {
  private queue: number[] = []          // 待加载的 pageNum 队列（按优先级）
  private running = new Set<number>()   // 正在加载的 pageNum
  private aborted = new Set<number>()   // 已被跳过的 pageNum

  request(pageNum: number, priority = false) {
    if (pageNum < 0 || pageNum >= pages.length) return
    const p = pages[pageNum]
    if (!p || p.rendered || p.loading) return
    if (this.running.has(pageNum)) return

    this.aborted.delete(pageNum)

    const idx = this.queue.indexOf(pageNum)
    if (idx >= 0) {
      if (priority) {
        this.queue.splice(idx, 1)
        this.queue.unshift(pageNum)
      }
      return
    }
    if (priority) this.queue.unshift(pageNum)
    else this.queue.push(pageNum)
    this.tick()
  }

  cancel(pageNum: number) {
    const idx = this.queue.indexOf(pageNum)
    if (idx >= 0) {
      this.queue.splice(idx, 1)
      this.aborted.add(pageNum)
    }
  }

  keepOnly(keepSet: Set<number>) {
    this.queue = this.queue.filter(pn => {
      if (keepSet.has(pn)) return true
      this.aborted.add(pn)
      return false
    })
  }

  private tick() {
    while (this.running.size < MAX_CONCURRENT && this.queue.length > 0) {
      const pageNum = this.queue.shift()!
      if (this.aborted.has(pageNum)) continue
      const p = pages[pageNum]
      if (!p || p.rendered || p.loading) continue

      this.running.add(pageNum)
      p.loading = true
      loadAndRender(pageNum)
        .then(() => this.markDone(pageNum))
        .catch(() => this.markError(pageNum))
    }
  }

  markDone(pageNum: number) {
    this.running.delete(pageNum)
    this.tick()
  }

  markError(pageNum: number) {
    this.running.delete(pageNum)
    this.tick()
  }

  clear() {
    this.queue = []
    this.running.clear()
    this.aborted.clear()
  }
}

const loader = new PageLoader()

// ============ URL 构建 ============
function buildPageUrl(pageNum: number): string {
  // 走 request 的 baseURL（相对路径），交给并发下载调度器
  // 页码对外统一 0-based（第一页 = 0），与 Rust 服务端约定一致
  return `pagepdf?id=${encodeURIComponent(bookId.value)}&page=${pageNum}`
}

// ============ 下载切片 + pdf.js 渲染 ============
async function loadAndRender(pageNum: number): Promise<void> {
  const p = pages[pageNum]
  if (!p) return

  // 1) 下载单页 PDF 切片（ArrayBuffer），复用 request.ts 的并发下载调度器
  const ac = new AbortController()
  pageAborts.set(pageNum, ac)
  let buf: ArrayBuffer
  try {
    buf = await download(buildPageUrl(pageNum), ac.signal)
  } finally {
    pageAborts.delete(pageNum)
  }

  // 2) pdf.js 解析（切片只有 1 页，取第 1 页）
  // 复制一份，避免 pdf.js 持有可能被复用的 buffer
  const data = buf.slice(0)
  const doc = await pdfjsLib.getDocument({data, disableAutoFetch: true, disableStream: true}).promise
  pageDocs.set(pageNum, doc)

  // 3) 渲染到 canvas
  await renderPageCanvas(pageNum)

  p.loading = false
  p.error = false
  p.rendered = true
}

// 把某页按当前 scale 渲染/重绘到它的 canvas
async function renderPageCanvas(pageNum: number): Promise<void> {
  const doc = pageDocs.get(pageNum)
  const canvas = canvasEls.get(pageNum)
  const p = pages[pageNum]
  if (!doc || !canvas || !p) return

  const pdfPage = await doc.getPage(1)
  const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR)
  // displayWidth 为 CSS 像素，viewport scale = (显示宽 / PDF 点宽) × dpr
  const cssWidth = p.displayWidth
  const baseViewport = pdfPage.getViewport({scale: 1})
  const renderScale = (cssWidth / baseViewport.width) * dpr
  const viewport = pdfPage.getViewport({scale: renderScale})

  const ctx = canvas.getContext('2d')
  if (!ctx) return
  canvas.width = Math.floor(viewport.width)
  canvas.height = Math.floor(viewport.height)
  canvas.style.width = '100%'
  canvas.style.height = '100%'

  await pdfPage.render({canvasContext: ctx, viewport}).promise
  // 释放该 page 的中间对象（保留 doc，供缩放重绘）
  pdfPage.cleanup()
}

// ============ 回收：滚出视区的页销毁 canvas 内容 + pdf.js 文档 ============
function recyclePage(pageNum: number) {
  const p = pages[pageNum]
  if (!p) return
  // 取消尚在下载的请求
  const ac = pageAborts.get(pageNum)
  if (ac) {
    ac.abort()
    pageAborts.delete(pageNum)
  }
  // 销毁 pdf.js 文档，释放内存
  const doc = pageDocs.get(pageNum)
  if (doc) {
    try { doc.destroy() } catch { /* ignore */ }
    pageDocs.delete(pageNum)
  }
  // 清空 canvas 位图
  const canvas = canvasEls.get(pageNum)
  if (canvas) {
    canvas.width = 0
    canvas.height = 0
  }
  p.rendered = false
  p.loading = false
  p.error = false
}

// ============ 回调 ============
function retryPage(pageNum: number) {
  const p = pages[pageNum]
  if (!p) return
  p.error = false
  p.rendered = false
  p.loading = false
  loader.request(pageNum, true)
}

// ============ IntersectionObserver 懒加载 ============
let io: IntersectionObserver | null = null

function setupObserver() {
  if (!viewportRef.value) return
  io = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      const pn = parseInt((entry.target as HTMLElement).dataset.pageNum || '-1', 10)
      if (pn < 0) continue
      if (entry.isIntersecting) {
        loader.request(pn, true)
        for (let k = 1; k <= PRELOAD_AHEAD; k++) loader.request(pn + k, false)
        for (let k = 1; k <= PRELOAD_BEHIND; k++) loader.request(pn - k, false)
      }
    }
  }, {
    root: viewportRef.value,
    rootMargin: OBSERVER_ROOT_MARGIN,
    threshold: 0.01,
  })
  const els = viewportRef.value.querySelectorAll('.image-page')
  els.forEach(el => io!.observe(el))
}

function teardownObserver() {
  if (io) {
    io.disconnect()
    io = null
  }
}

// ============ 尺寸计算 ============
function computeDisplaySize(p: PageItem) {
  const vw = Math.min(
      (viewportRef.value?.clientWidth || 800) - 24,
      VIEWPORT_WIDTH_LIMIT
  )
  const ratio = p.origHeight / p.origWidth
  const baseWidth = Math.min(vw, p.origWidth * 1.2)
  p.displayWidth = Math.round(baseWidth * scale.value)
  p.displayHeight = Math.round(p.displayWidth * ratio)
}

function recomputeAllSizes() {
  for (const p of pages) computeDisplaySize(p)
}

// ============ 滚动处理 ============
const handleScroll = () => {
  updateCurrentPageFromScroll()
  scheduleCancelInvisible()
}

function updateCurrentPageFromScroll() {
  const vp = viewportRef.value
  if (!vp) return
  const scrollTop = vp.scrollTop
  const viewCenter = scrollTop + vp.clientHeight / 2

  let acc = 0
  for (let i = 0; i < pages.length; i++) {
    const h = pages[i].displayHeight + 20 // 20 = margin-bottom
    if (viewCenter >= acc && viewCenter < acc + h) {
      currentPage.value = i
      const inPageFrac = Math.min(1, Math.max(0, (viewCenter - acc) / h))
      saveProgress(i, inPageFrac)
      return
    }
    acc += h
  }
}

// 快速滚动时，取消/回收远离视口的页
const scheduleCancelInvisible = debounce(() => {
  const vp = viewportRef.value
  if (!vp) return
  const scrollTop = vp.scrollTop
  const viewBottom = scrollTop + vp.clientHeight

  const keep = new Set<number>()
  let acc = 0
  const buffer = vp.clientHeight * 2 // 上下2屏范围内保留
  for (let i = 0; i < pages.length; i++) {
    const h = pages[i].displayHeight + 20
    const top = acc
    const bottom = acc + h
    if (bottom >= scrollTop - buffer && top <= viewBottom + buffer) {
      keep.add(i)
    }
    acc += h
  }
  loader.keepOnly(keep)
  // 回收保留范围之外、已渲染的页，释放 pdf.js 内存（手机端翻几十页不 OOM）
  for (const p of pages) {
    if (!keep.has(p.pageNum) && (p.rendered || pageDocs.has(p.pageNum))) {
      recyclePage(p.pageNum)
    }
  }
}, 200)

// ============ 进度保存 ============
const saveProgress = debounce(async (pageNum: number, fraction: number) => {
  if (!bookId.value) return
  try {
    await request.post(`progress?id=${bookId.value}`, {
      page: pageNum,
      frac: fraction,
      name: bookName.value,
      scale: scale.value,
      totalPages: total.value,
      percent: ((pageNum + 1) / total.value * 100).toFixed(2),
    }, {headers: {'Content-Type': 'application/json'}})
  } catch (e) {
    console.warn('保存进度失败', e)
  }
}, 800)

// ============ 元数据加载 ============
async function loadMeta() {
  try {
    const response = await request.get(`meta?id=${bookId.value}`)
    const data = response.data

    total.value = data.pageCount || 0
    bookName.value = data.name || ''
    currentPage.value = data.progress?.page || 0
    startFrac.value = typeof data.progress?.frac === 'number' ? data.progress.frac : 0

    pages.length = 0
    const metaPages: Array<{ w: number; h: number }> = data.pages || []
    for (let i = 0; i < total.value; i++) {
      const size = metaPages[i]
      const item: PageItem = {
        pageNum: i,
        origWidth: size?.w || DEFAULT_PAGE_WIDTH,
        origHeight: size?.h || DEFAULT_PAGE_HEIGHT,
        displayWidth: 0,
        displayHeight: 0,
        loading: false,
        rendered: false,
        error: false,
      }
      computeDisplaySize(item)
      pages.push(item)
    }

    console.log('📚 PDF 阅读器已初始化', {
      文档: bookName.value,
      总页数: total.value,
      起始页: currentPage.value + 1,
    })

    await nextTick()
    setupObserver()
    scrollToPage(currentPage.value, startFrac.value)
  } catch (e) {
    console.error('加载文档元数据失败', e)
  }
}

function scrollToPage(pageNum: number, frac = 0) {
  const vp = viewportRef.value
  if (!vp) return
  let top = 0
  for (let i = 0; i < pageNum && i < pages.length; i++) {
    top += pages[i].displayHeight + 20
  }
  const h = (pages[pageNum]?.displayHeight || 0) + 20
  top += h * frac - vp.clientHeight / 2
  vp.scrollTop = Math.max(0, top)
}

// ============ 缩放 ============
// 重绘节流：缩放停止后再按新 scale 重渲染可视页 canvas（矢量始终清晰）
const rerenderVisible = debounce(() => {
  for (const [pageNum] of pageDocs) {
    renderPageCanvas(pageNum).catch(() => { /* ignore */ })
  }
}, 200)

function applyZoom(newScale: number, anchorClientY?: number) {
  newScale = Math.min(MAX_SCALE, Math.max(MIN_SCALE, newScale))
  const vp = viewportRef.value
  if (!vp) {
    scale.value = newScale
    recomputeAllSizes()
    return
  }

  const anchorY = anchorClientY ?? vp.clientHeight / 2
  const scrollTop = vp.scrollTop
  const focus = scrollTop + anchorY

  let acc = 0
  let anchorPage = 0
  let anchorRatio = 0
  for (let i = 0; i < pages.length; i++) {
    const h = pages[i].displayHeight + 20
    if (focus >= acc && focus < acc + h) {
      anchorPage = i
      anchorRatio = (focus - acc) / h
      break
    }
    acc += h
  }

  scale.value = newScale
  recomputeAllSizes()

  nextTick(() => {
    let top = 0
    for (let i = 0; i < anchorPage && i < pages.length; i++) {
      top += pages[i].displayHeight + 20
    }
    top += ((pages[anchorPage]?.displayHeight || 0) + 20) * anchorRatio
    vp.scrollTop = Math.max(0, top - anchorY)
  })
  // 按新 scale 重绘已加载页的 canvas，保证矢量清晰不发虚
  rerenderVisible()
}

function zoomIn() {
  const next = zoomLevels.find(z => z > scale.value + 1e-6)
  if (next !== undefined) applyZoom(next)
}

function zoomOut() {
  const prev = [...zoomLevels].reverse().find(z => z < scale.value - 1e-6)
  if (prev !== undefined) applyZoom(prev)
}

// ============ 双指缩放手势 ============
let pinchStartDist = 0
let pinchStartScale = 1
let pinchAnchorY = 0
let pinching = false

function touchDist(t0: Touch, t1: Touch) {
  const dx = t0.clientX - t1.clientX
  const dy = t0.clientY - t1.clientY
  return Math.hypot(dx, dy)
}

function onTouchStart(e: TouchEvent) {
  if (e.touches.length === 2) {
    pinching = true
    pinchStartDist = touchDist(e.touches[0], e.touches[1])
    pinchStartScale = scale.value
    const vp = viewportRef.value
    const midY = (e.touches[0].clientY + e.touches[1].clientY) / 2
    pinchAnchorY = vp ? midY - vp.getBoundingClientRect().top : midY
  }
}

function onTouchMove(e: TouchEvent) {
  if (!pinching || e.touches.length !== 2) return
  e.preventDefault()
  const dist = touchDist(e.touches[0], e.touches[1])
  if (pinchStartDist <= 0) return
  const target = pinchStartScale * (dist / pinchStartDist)
  applyZoom(target, pinchAnchorY)
}

function onTouchEnd(e: TouchEvent) {
  if (e.touches.length < 2) pinching = false
}

// ============ 生命周期 ============
onMounted(async () => {
  bookId.value = route.params.bookId as string
  await loadMeta()
  const vp = viewportRef.value
  if (vp) {
    vp.addEventListener('touchstart', onTouchStart, {passive: true})
    vp.addEventListener('touchmove', onTouchMove, {passive: false})
    vp.addEventListener('touchend', onTouchEnd, {passive: true})
    vp.addEventListener('touchcancel', onTouchEnd, {passive: true})
  }
})

onUnmounted(() => {
  const vp = viewportRef.value
  if (vp) {
    vp.removeEventListener('touchstart', onTouchStart)
    vp.removeEventListener('touchmove', onTouchMove)
    vp.removeEventListener('touchend', onTouchEnd)
    vp.removeEventListener('touchcancel', onTouchEnd)
  }
  teardownObserver()
  loader.clear()
  // 释放所有 pdf.js 文档
  for (const [pn] of pageDocs) recyclePage(pn)
  pageDocs.clear()
  canvasEls.clear()
  pages.length = 0
})

function close() {
  router.back()
}
</script>

<style scoped>
.reader {
  height: 100vh;
  display: flex;
  flex-direction: column;
}

.reader-toolbar {
  flex: 0 0 46px;
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 14px;
  background: var(--panel);
  border-bottom: 1px solid var(--border);
  overflow-x: auto;
  overflow-y: hidden;
  -webkit-overflow-scrolling: touch;
  scrollbar-width: none;
  -ms-overflow-style: none;
}

.reader-toolbar::-webkit-scrollbar {
  display: none;
  height: 0;
}

.reader-toolbar > * {
  flex: 0 0 auto;
}

.reader-toolbar .doc-title {
  font-size: 13px;
  font-weight: 500;
  max-width: 32vw;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.spacer {
  flex: 1;
}

.pageinfo {
  font-size: 14px;
}

.zoom {
  min-width: 40px;
  text-align: center;
}

.btn {
  border: none;
  background: none;
  font-size: 18px;
}

.image-viewport {
  flex: 1;
  overflow-y: auto;
  overflow-x: auto;
  position: relative;
  background: #f5f5f5;
  padding: 12px 0;
  -webkit-overflow-scrolling: touch;
  touch-action: pan-x pan-y;
  overscroll-behavior: contain;
}

.pages-track {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: max-content;
  min-width: 100%;
  box-sizing: border-box;
  padding: 0 12px;
}

.image-page {
  position: relative;
  background: #fff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin: 0 0 20px;
  overflow: hidden;
  contain: layout paint;
  flex: 0 0 auto;
}

.page-canvas {
  width: 100%;
  height: 100%;
  display: block;
}

.ph-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  color: #b3bccb;
  background: linear-gradient(135deg, #f4f7fc, #e9eef7);
  pointer-events: none;
}

.ph-icon svg {
  width: 42px;
  height: 42px;
}

.ph-text {
  font-size: 12px;
  color: #99a3b3;
}

.err-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.9);
  font-size: 13px;
  color: #f56c6c;
  cursor: pointer;
}

.page-footer {
  display: none;
  position: fixed;
  left: 50%;
  bottom: 12px;
  transform: translateX(-50%);
  padding: 4px 12px;
  border-radius: 999px;
  background: rgba(0, 0, 0, 0.55);
  color: #fff;
  font-size: 12px;
  line-height: 1;
  z-index: 20;
  pointer-events: none;
  backdrop-filter: blur(4px);
}

/* ============ 手机端适配 ============ */
@media (max-width: 640px) {
  .reader-toolbar {
    display: none;
  }

  .page-footer {
    display: block;
  }
}
</style>

// reactapp/src/components/PdfReader.tsx
import {memo, useCallback, useEffect, useRef, useState} from 'react'
import {useNavigate, useParams} from 'react-router-dom'
import {download, request} from '../utils/request'
import {debounce} from '../utils/UIUtils'
import {MAX_DPR, pdfjsLib} from '../pdf'
import '../PdfReader.css'

// ============ 缩放常量 ============
const MIN_SCALE = 0.5
const MAX_SCALE = 3
const zoomLevels = [0.5, 0.75, 1, 1.25, 1.5, 2, 3]
const ZOOM_STORE_KEY = 'pdfreader.zoom.scale'

// ============ 加载/布局常量 ============
const MAX_CONCURRENT = 3
const PRELOAD_AHEAD = 2
const PRELOAD_BEHIND = 1
const OBSERVER_ROOT_MARGIN = '400px 0px'
const DEFAULT_PAGE_WIDTH = 595
const DEFAULT_PAGE_HEIGHT = 842
// .image-viewport 上内边距（CSS padding:12px 0）与 .pages-track 左内边距（padding:0 12px）。
const VIEWPORT_PAD_TOP = 12
const TRACK_PAD_LEFT = 12

// ============ 缩放比例本地持久化（按设备，localStorage）============
function loadLocalScale(): number {
    try {
        const raw = localStorage.getItem(ZOOM_STORE_KEY)
        if (raw == null) return 1
        const v = parseFloat(raw)
        if (!isFinite(v)) return 1
        return Math.min(MAX_SCALE, Math.max(MIN_SCALE, v))
    } catch {
        return 1
    }
}

function saveLocalScale(v: number) {
    try {
        localStorage.setItem(ZOOM_STORE_KEY, String(v))
    } catch { /* 隐私模式等静默忽略 */ }
}

interface PageItem {
    pageNum: number
    origWidth: number   // 原始 pt（来自 meta 或 pdf.js 校正）
    origHeight: number
    ratio: number       // origHeight / origWidth，用于 JS 算高度
    loading: boolean
    rendered: boolean
    error: boolean
}

// ============ 并发调度器（下载切片 + pdf.js 渲染）============
class PageLoader {
    private queue: number[] = []
    private running = new Set<number>()
    private aborted = new Set<number>()

    constructor(
        private getPage: (n: number) => PageItem | undefined,
        private pageCount: () => number,
        private doLoad: (n: number) => Promise<void>,
    ) {}

    request(pageNum: number, priority = false) {
        if (pageNum < 0 || pageNum >= this.pageCount()) return
        const p = this.getPage(pageNum)
        if (!p || p.rendered || p.loading) return
        if (this.running.has(pageNum)) return
        this.aborted.delete(pageNum)
        const idx = this.queue.indexOf(pageNum)
        if (idx >= 0) {
            if (priority) {
                this.queue.splice(idx, 1)
                this.queue.unshift(pageNum)
            }
            return
        }
        if (priority) this.queue.unshift(pageNum)
        else this.queue.push(pageNum)
        this.tick()
    }

    keepOnly(keepSet: Set<number>) {
        this.queue = this.queue.filter(pn => {
            if (keepSet.has(pn)) return true
            this.aborted.add(pn)
            return false
        })
    }

    private tick() {
        while (this.running.size < MAX_CONCURRENT && this.queue.length > 0) {
            const pageNum = this.queue.shift()!
            if (this.aborted.has(pageNum)) continue
            const p = this.getPage(pageNum)
            if (!p || p.rendered || p.loading) continue
            this.running.add(pageNum)
            this.doLoad(pageNum)
                .catch(() => { /* 失败由调用方标 error */ })
                .finally(() => {
                    this.running.delete(pageNum)
                    this.tick()
                })
        }
    }

    clear() {
        this.queue = []
        this.running.clear()
        this.aborted.clear()
    }
}

// ============ 单页组件（memo：只有该页状态变化才重渲染）============
const PdfPage = memo(function PdfPage(props: {
    page: PageItem
    setCanvasRef: (pn: number, el: HTMLCanvasElement | null) => void
    onRetry: (pn: number) => void
}) {
    const {page, setCanvasRef, onRetry} = props
    return (
        <div
            className="image-page"
            data-page-num={page.pageNum}
            style={{
                width: 'var(--pagew)',
                aspectRatio: `${page.origWidth} / ${page.origHeight}`,
            }}
        >
            <canvas
                ref={(el) => setCanvasRef(page.pageNum, el)}
                className="page-canvas"
                style={{display: page.rendered ? 'block' : 'none'}}
            />
            {!page.rendered && !page.error && (
                <div className="ph-overlay">
                    <div className="ph-icon">
                        <svg viewBox="0 0 24 24" fill="none">
                            <path d="M6 2h8l4 4v16H6z" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round"/>
                            <path d="M14 2v4h4" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round"/>
                        </svg>
                    </div>
                    <div className="ph-text">
                        {page.loading ? `加载中 ${page.pageNum + 1}...` : `第 ${page.pageNum + 1} 页`}
                    </div>
                </div>
            )}
            {page.error && (
                <div className="err-overlay" onClick={() => onRetry(page.pageNum)}>
                    <div>加载失败，点击重试</div>
                </div>
            )}
        </div>
    )
})

export default function PdfReader() {
    const {bookId = ''} = useParams()
    const navigate = useNavigate()
    const viewportRef = useRef<HTMLDivElement>(null)
    const trackRef = useRef<HTMLDivElement>(null)

    // UI 状态（驱动渲染的少量状态）
    const [bookName, setBookName] = useState('')
    const [total, setTotal] = useState(0)
    const [currentPage, setCurrentPage] = useState(0)
    const [scale, setScaleState] = useState(loadLocalScale())
    const [pages, setPagesState] = useState<PageItem[]>([])

    // 同步 ref：手势/异步回调里读最新值（避免 React 闭包旧值）
    const scaleRef = useRef(scale)
    const pagesRef = useRef<PageItem[]>(pages)
    const totalRef = useRef(0)
    const startFracRef = useRef(0)
    const stableClientWidthRef = useRef(0)
    const canvasElsRef = useRef(new Map<number, HTMLCanvasElement>())
    const pageDocsRef = useRef(new Map<number, any>())
    const pageAbortsRef = useRef(new Map<number, AbortController>())
    const ioRef = useRef<IntersectionObserver | null>(null)

    // 双指手势状态（全部走 ref，高频 touchmove 里读最新值）
    const pinchRef = useRef({
        startDist: 0, startScale: 1, contentX: 0, contentY: 0,
        lastMidX: 0, lastMidY: 0, pendingScale: 1, rafPending: false,
        vpRect: null as DOMRect | null, pinching: false, lastEndTime: 0,
    })
    // 首次初始化标记 + 待恢复进度（loadMeta 设置，useEffect 在 DOM 就绪后消费）
    const initializedRef = useRef(false)
    const pendingInitRef = useRef<{ page: number, frac: number } | null>(null)

    const setScale = (v: number) => {
        scaleRef.current = v
        setScaleState(v)
    }
    const setPages = (arr: PageItem[]) => {
        pagesRef.current = arr
        setPagesState(arr)
    }
    const updatePage = (pageNum: number, patch: Partial<PageItem>) => {
        const next = pagesRef.current.map(p => p.pageNum === pageNum ? {...p, ...patch} : p)
        pagesRef.current = next
        setPagesState(next)
    }

    // ============ 尺寸计算 ============
    // 页宽 = (稳定视口宽 - 轨道左右 padding 24) × scale。所有页等宽（CSS 变量驱动）。
    const computePageWidth = () => {
        const vw = (stableClientWidthRef.current || 800) - 24
        return Math.round(vw * scaleRef.current)
    }
    // 页高 = 页宽 × ratio（ratio = origHeight/origWidth，aspect-ratio 也据此自动撑高）
    const pageDisplayHeight = (p: PageItem) => Math.round(computePageWidth() * p.ratio)

    // 把页宽写进 CSS 变量 --pagew + 精确设定 track 宽度（不靠 max-content，iOS 白屏重绘会算错）。
    // 这是缩放唯一改 DOM 的地方；page 尺寸由 CSS 变量 + aspect-ratio 自动跟随，零 React 列表重渲染。
    const applyTrackWidth = () => {
        const track = trackRef.current
        const vp = viewportRef.current
        if (!track || !vp) return
        const pw = computePageWidth()
        track.style.setProperty('--pagew', pw + 'px')
        track.style.width = Math.max(pw + 24, vp.clientWidth) + 'px'
    }

    const refreshStableWidth = () => {
        const w = viewportRef.current?.clientWidth || 0
        if (w > 0) stableClientWidthRef.current = w
    }

    // ============ canvas 引用 ============
    const setCanvasRef = useCallback((pageNum: number, el: HTMLCanvasElement | null) => {
        if (el) canvasElsRef.current.set(pageNum, el)
        else canvasElsRef.current.delete(pageNum)
    }, [])

    // ============ 下载切片 + pdf.js 渲染 ============
    const renderPageCanvas = useCallback(async (pageNum: number): Promise<void> => {
        const doc = pageDocsRef.current.get(pageNum)
        const canvas = canvasElsRef.current.get(pageNum)
        const p = pagesRef.current[pageNum]
        if (!doc || !canvas || !p) return

        const pdfPage = await doc.getPage(1)
        const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR)
        const baseViewport = pdfPage.getViewport({scale: 1})

        // 以 pdf.js 实际渲染尺寸校正该页比例（meta 是 MediaBox，pdf.js 用 CropBox）。
        if (baseViewport.width > 0 && baseViewport.height > 0) {
            const realRatio = baseViewport.height / baseViewport.width
            if (!isFinite(p.ratio) || Math.abs(realRatio - p.ratio) > 0.003) {
                updatePage(pageNum, {
                    origWidth: baseViewport.width,
                    origHeight: baseViewport.height,
                    ratio: realRatio,
                })
            }
        }

        const cssWidth = computePageWidth()
        const renderScale = (cssWidth / baseViewport.width) * dpr
        const viewport = pdfPage.getViewport({scale: renderScale})
        const ctx = canvas.getContext('2d')
        if (!ctx) return
        canvas.width = Math.floor(viewport.width)
        canvas.height = Math.floor(viewport.height)
        canvas.style.width = '100%'
        canvas.style.height = '100%'
        await pdfPage.render({canvasContext: ctx, viewport}).promise
        pdfPage.cleanup()
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    const loadAndRender = useCallback(async (pageNum: number): Promise<void> => {
        const p = pagesRef.current[pageNum]
        if (!p) return
        const ac = new AbortController()
        pageAbortsRef.current.set(pageNum, ac)
        let buf: ArrayBuffer
        try {
            buf = await download(`pagepdf?id=${encodeURIComponent(bookId)}&page=${pageNum}`, ac.signal)
        } finally {
            pageAbortsRef.current.delete(pageNum)
        }
        const data = buf.slice(0)
        const doc = await pdfjsLib.getDocument({data, disableAutoFetch: true, disableStream: true}).promise
        pageDocsRef.current.set(pageNum, doc)
        await renderPageCanvas(pageNum)
        updatePage(pageNum, {loading: false, error: false, rendered: true})
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [bookId, renderPageCanvas])

    const loaderRef = useRef<PageLoader>()
    if (!loaderRef.current) {
        loaderRef.current = new PageLoader(
            (n) => pagesRef.current[n],
            () => pagesRef.current.length,
            async (n) => {
                updatePage(n, {loading: true})
                try {
                    await loadAndRender(n)
                } catch {
                    updatePage(n, {loading: false, error: true})
                }
            },
        )
    }

    // ============ 回收：滚出视区的页销毁 canvas + pdf.js 文档 ============
    const recyclePage = useCallback((pageNum: number) => {
        const p = pagesRef.current[pageNum]
        if (!p) return
        const ac = pageAbortsRef.current.get(pageNum)
        if (ac) {
            ac.abort()
            pageAbortsRef.current.delete(pageNum)
        }
        const doc = pageDocsRef.current.get(pageNum)
        if (doc) {
            try {
                doc.destroy()
            } catch { /* ignore */ }
            pageDocsRef.current.delete(pageNum)
        }
        const canvas = canvasElsRef.current.get(pageNum)
        if (canvas) {
            canvas.width = 0
            canvas.height = 0
        }
        updatePage(pageNum, {rendered: false, loading: false, error: false})
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    const retryPage = useCallback((pageNum: number) => {
        updatePage(pageNum, {error: false, rendered: false, loading: false})
        loaderRef.current?.request(pageNum, true)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // ============ IntersectionObserver 懒加载 ============
    const setupObserver = useCallback(() => {
        const vp = viewportRef.current
        if (!vp) return
        ioRef.current = new IntersectionObserver((entries) => {
            for (const entry of entries) {
                const pn = parseInt((entry.target as HTMLElement).dataset.pageNum || '-1', 10)
                if (pn < 0) continue
                if (entry.isIntersecting) {
                    loaderRef.current?.request(pn, true)
                    for (let k = 1; k <= PRELOAD_AHEAD; k++) loaderRef.current?.request(pn + k, false)
                    for (let k = 1; k <= PRELOAD_BEHIND; k++) loaderRef.current?.request(pn - k, false)
                }
            }
        }, {root: vp, rootMargin: OBSERVER_ROOT_MARGIN, threshold: 0.01})
        const els = vp.querySelectorAll('.image-page')
        els.forEach(el => ioRef.current!.observe(el))
    }, [])

    const teardownObserver = useCallback(() => {
        ioRef.current?.disconnect()
        ioRef.current = null
    }, [])

    // ============ 滚动处理 ============
    const saveProgress = useRef(debounce(async (pageNum: number, fraction: number) => {
        if (!bookId) return
        try {
            await request.post(`progress?id=${bookId}`, {
                page: pageNum,
                frac: fraction,
                name: bookName,
                scale: scaleRef.current,
                totalPages: totalRef.current,
                percent: ((pageNum + 1) / totalRef.current * 100).toFixed(2),
            }, {headers: {'Content-Type': 'application/json'}})
        } catch (e) {
            console.warn('保存进度失败', e)
        }
    }, 800)).current

    const updateCurrentPageFromScroll = useCallback(() => {
        const vp = viewportRef.current
        if (!vp) return
        const scrollTop = vp.scrollTop
        const viewCenter = scrollTop + vp.clientHeight / 2
        let acc = 0
        const list = pagesRef.current
        for (let i = 0; i < list.length; i++) {
            const h = pageDisplayHeight(list[i]) + 20
            if (viewCenter >= acc && viewCenter < acc + h) {
                setCurrentPage(i)
                saveProgress(i, Math.min(1, Math.max(0, (viewCenter - acc) / h)))
                return
            }
            acc += h
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [saveProgress])

    const scheduleCancelInvisible = useRef(debounce(() => {
        const vp = viewportRef.current
        if (!vp) return
        const scrollTop = vp.scrollTop
        const viewBottom = scrollTop + vp.clientHeight
        const keep = new Set<number>()
        let acc = 0
        const buffer = vp.clientHeight * 2
        const list = pagesRef.current
        for (let i = 0; i < list.length; i++) {
            const h = pageDisplayHeight(list[i]) + 20
            const top = acc
            const bottom = acc + h
            if (bottom >= scrollTop - buffer && top <= viewBottom + buffer) keep.add(i)
            acc += h
        }
        loaderRef.current?.keepOnly(keep)
        for (const p of list) {
            if (!keep.has(p.pageNum) && (p.rendered || pageDocsRef.current.has(p.pageNum))) {
                recyclePage(p.pageNum)
            }
        }
    }, 200)).current

    const handleScroll = useCallback(() => {
        updateCurrentPageFromScroll()
        scheduleCancelInvisible()
    }, [updateCurrentPageFromScroll, scheduleCancelInvisible])

    // ============ 横向居中 ============
    // 内容(track)比视口宽时，把横向滚动停在正中；不宽时 scrollLeft 归 0 天然居中。
    const centerHorizontally = useCallback(() => {
        const vp = viewportRef.current
        if (!vp) return
        const extra = vp.scrollWidth - vp.clientWidth
        vp.scrollLeft = extra > 0 ? Math.round(extra / 2) : 0
    }, [])

    // ============ 重绘节流：缩放停止后按新 scale 重渲染可视页 canvas ============
    const rerenderVisible = useRef(debounce(() => {
        for (const [pageNum] of pageDocsRef.current) {
            renderPageCanvas(pageNum).catch(() => { /* ignore */ })
        }
    }, 200)).current

    // ============ 进度恢复滚动 ============
    const scrollToPage = useCallback((pageNum: number, frac = 0) => {
        const vp = viewportRef.current
        if (!vp) return
        let top = 0
        const list = pagesRef.current
        for (let i = 0; i < pageNum && i < list.length; i++) top += pageDisplayHeight(list[i]) + 20
        const h = (list[pageNum] ? pageDisplayHeight(list[pageNum]) : 0) + 20
        top += h * frac - vp.clientHeight / 2
        vp.scrollTop = Math.max(0, top)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // ============ 元数据加载 ============
    const loadMeta = useCallback(async () => {
        try {
            const response = await request.get(`meta?id=${bookId}`)
            const data = response.data
            const cnt = data.pageCount || 0
            totalRef.current = cnt
            setTotal(cnt)
            setBookName(data.name || '')
            setCurrentPage(data.progress?.page || 0)
            startFracRef.current = typeof data.progress?.frac === 'number' ? data.progress.frac : 0

            refreshStableWidth()
            const metaPages: Array<{ w: number; h: number }> = data.pages || []
            const list: PageItem[] = []
            for (let i = 0; i < cnt; i++) {
                const w = metaPages[i]?.w || DEFAULT_PAGE_WIDTH
                const h = metaPages[i]?.h || DEFAULT_PAGE_HEIGHT
                list.push({
                    pageNum: i,
                    origWidth: w,
                    origHeight: h,
                    ratio: h / w,
                    loading: false,
                    rendered: false,
                    error: false,
                })
            }
            setPages(list)
            // 记录待恢复进度，由 useEffect[pages] 在 DOM 就绪后消费（初始化 observer + 滚动定位）。
            pendingInitRef.current = {page: data.progress?.page || 0, frac: startFracRef.current}

            console.log('📚 PDF 阅读器已初始化', {文档: data.name, 总页数: cnt, 起始页: (data.progress?.page || 0) + 1})
        } catch (e) {
            console.error('加载文档元数据失败', e)
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [bookId])

    // ============ 按钮缩放 ============
    const applyZoom = useCallback((newScale: number) => {
        newScale = Math.min(MAX_SCALE, Math.max(MIN_SCALE, newScale))
        const vp = viewportRef.current
        if (!vp) {
            setScale(newScale)
            applyTrackWidth()
            return
        }
        const anchorY = vp.clientHeight / 2
        const scrollTop = vp.scrollTop
        const focus = scrollTop + anchorY
        const list = pagesRef.current
        let acc = 0, anchorPage = 0, anchorRatio = 0
        for (let i = 0; i < list.length; i++) {
            const h = pageDisplayHeight(list[i]) + 20
            if (focus >= acc && focus < acc + h) {
                anchorPage = i
                anchorRatio = (focus - acc) / h
                break
            }
            acc += h
        }
        setScale(newScale)
        saveLocalScale(newScale)
        applyTrackWidth()
        // track 宽度/DOM 已同步更新（读取 scroll 会强制 reflow）
        let top = 0
        for (let i = 0; i < anchorPage && i < list.length; i++) top += pageDisplayHeight(list[i]) + 20
        top += ((list[anchorPage] ? pageDisplayHeight(list[anchorPage]) : 0) + 20) * anchorRatio
        vp.scrollTop = Math.max(0, top - anchorY)
        centerHorizontally()
        rerenderVisible()
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [centerHorizontally, rerenderVisible])

    const zoomIn = () => {
        const next = zoomLevels.find(z => z > scaleRef.current + 1e-6)
        if (next !== undefined) applyZoom(next)
    }
    const zoomOut = () => {
        const prev = [...zoomLevels].reverse().find(z => z < scaleRef.current - 1e-6)
        if (prev !== undefined) applyZoom(prev)
    }

    // ============ 双指缩放手势 ============
    // scale 是唯一数据源；手势中实时改 scale + applyTrackWidth（DOM），并用 scrollTop/scrollLeft
    // 让「双指中心指向的内容点」始终跟随双指 —— 纯滚动锚定，绝不用 transform。
    // 居中靠 page 的 block margin:0 auto 天然保证。手势中 canvas 不重绘（CSS 变量拉伸），松手重绘高清。
    const touchDist = (t0: Touch, t1: Touch) => Math.hypot(t0.clientX - t1.clientX, t0.clientY - t1.clientY)

    const onTouchStart = (e: TouchEvent) => {
        if (e.touches.length !== 2) return
        const vp = viewportRef.current
        if (!vp) return
        const S = pinchRef.current
        S.pinching = true
        S.startDist = touchDist(e.touches[0], e.touches[1])
        S.startScale = scaleRef.current
        S.vpRect = vp.getBoundingClientRect()
        const midX = (e.touches[0].clientX + e.touches[1].clientX) / 2
        const midY = (e.touches[0].clientY + e.touches[1].clientY) / 2
        S.lastMidX = midX
        S.lastMidY = midY
        // 锁定双指中心指向的内容坐标（当前 scale 布局下）：
        // 水平：page 左边缘屏幕 X = rect.left - scrollLeft + TRACK_PAD_LEFT
        // 垂直：第一页顶部屏幕 Y = rect.top + VIEWPORT_PAD_TOP - scrollTop
        S.contentX = (midX - S.vpRect.left) + vp.scrollLeft - TRACK_PAD_LEFT
        S.contentY = (midY - S.vpRect.top) + vp.scrollTop - VIEWPORT_PAD_TOP
    }

    const applyPinchFrame = (newScale: number) => {
        const vp = viewportRef.current
        const S = pinchRef.current
        if (!vp || !S.vpRect) return
        const k = newScale / S.startScale
        setScale(newScale)      // 更新 zoomLabel + scaleRef
        applyTrackWidth()       // 改 --pagew + track 宽度（DOM），浏览器随即 reflow
        // 内容点新坐标 = 旧 × k；让其屏幕位置 = 当前双指中心。
        vp.scrollTop = S.contentY * k - (S.lastMidY - S.vpRect.top) + VIEWPORT_PAD_TOP
        vp.scrollLeft = S.contentX * k - (S.lastMidX - S.vpRect.left) + TRACK_PAD_LEFT
    }

    const schedulePinchFrame = () => {
        const S = pinchRef.current
        if (S.rafPending) return
        S.rafPending = true
        requestAnimationFrame(() => {
            S.rafPending = false
            applyPinchFrame(S.pendingScale)
        })
    }

    const onTouchMove = (e: TouchEvent) => {
        const S = pinchRef.current
        if (!S.pinching || e.touches.length !== 2) return
        e.preventDefault()
        const dist = touchDist(e.touches[0], e.touches[1])
        if (S.startDist <= 0) return
        S.lastMidX = (e.touches[0].clientX + e.touches[1].clientX) / 2
        S.lastMidY = (e.touches[0].clientY + e.touches[1].clientY) / 2
        const ratio = dist / S.startDist
        S.pendingScale = Math.min(MAX_SCALE, Math.max(MIN_SCALE, S.startScale * ratio))
        schedulePinchFrame()
    }

    const onTouchEnd = (e: TouchEvent) => {
        if (e.touches.length >= 2) return
        const S = pinchRef.current
        if (!S.pinching) return
        S.pinching = false
        S.vpRect = null
        S.lastEndTime = Date.now() // 供 handleResize 豁免判断
        saveLocalScale(scaleRef.current)
        rerenderVisible()
    }

    // ============ 窗口尺寸变化（含 iOS 手势/地址栏误触发豁免）============
    const handleResize = useRef(debounce(() => {
        const S = pinchRef.current
        // 双指手势期间及松手后豁免窗口内忽略 resize：此时多为 iOS 捏合/地址栏显隐误触发，
        // 若照常重排 + centerHorizontally 会覆盖双指锚定的 scroll，导致布局错乱。
        if (S.pinching || Date.now() - S.lastEndTime < 500) return
        const list = pagesRef.current
        if (!list.length) return
        const vp = viewportRef.current
        let anchorPage = 0, anchorRatio = 0
        if (vp) {
            const focus = vp.scrollTop + vp.clientHeight / 2
            let acc = 0
            for (let i = 0; i < list.length; i++) {
                const h = pageDisplayHeight(list[i]) + 20
                if (focus >= acc && focus < acc + h) {
                    anchorPage = i
                    anchorRatio = (focus - acc) / h
                    break
                }
                acc += h
            }
        }
        refreshStableWidth()
        applyTrackWidth()
        if (vp) {
            let top = 0
            for (let i = 0; i < anchorPage && i < list.length; i++) top += pageDisplayHeight(list[i]) + 20
            top += ((list[anchorPage] ? pageDisplayHeight(list[anchorPage]) : 0) + 20) * anchorRatio
            vp.scrollTop = Math.max(0, top - vp.clientHeight / 2)
            centerHorizontally()
        }
        rerenderVisible()
    }, 200)).current

    // ============ 首次初始化 ============
    // pages 渲染出 DOM 后，挂 observer + 恢复进度滚动 + 居中。用 useEffect 而非
    // loadMeta 里的 rAF/flushSync —— React 保证 effect 在 DOM 更新后执行，时序可靠。
    useEffect(() => {
        if (pages.length === 0 || initializedRef.current) return
        initializedRef.current = true
        applyTrackWidth()
        setupObserver()
        const pend = pendingInitRef.current
        if (pend) scrollToPage(pend.page, pend.frac)
        centerHorizontally()
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pages])

    // ============ 生命周期 ============
    useEffect(() => {
        loadMeta()
        const vp = viewportRef.current
        if (vp) {
            vp.addEventListener('touchstart', onTouchStart, {passive: true})
            vp.addEventListener('touchmove', onTouchMove, {passive: false})
            vp.addEventListener('touchend', onTouchEnd, {passive: true})
            vp.addEventListener('touchcancel', onTouchEnd, {passive: true})
        }
        window.addEventListener('resize', handleResize)
        return () => {
            if (vp) {
                vp.removeEventListener('touchstart', onTouchStart)
                vp.removeEventListener('touchmove', onTouchMove)
                vp.removeEventListener('touchend', onTouchEnd)
                vp.removeEventListener('touchcancel', onTouchEnd)
            }
            window.removeEventListener('resize', handleResize)
            teardownObserver()
            loaderRef.current?.clear()
            for (const [pn] of pageDocsRef.current) recyclePage(pn)
            pageDocsRef.current.clear()
            canvasElsRef.current.clear()
            setPages([])
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [bookId])

    const close = () => navigate(-1)

    const zoomLabel = `${Math.round(scale * 100)}%`

    return (
        <div className="reader">
            {/* 工具栏（手机端隐藏，改用页脚页码 + 双指缩放）*/}
            <div className="reader-toolbar">
                <button className="btn btn-back" onClick={close}>← 返回</button>
                <span className="doc-title">{bookName}</span>
                <div className="spacer"/>
                <span className="pageinfo">{currentPage + 1} / {total}</span>
                <button className="btn" onClick={zoomOut}>－</button>
                <span className="zoom">{zoomLabel}</span>
                <button className="btn" onClick={zoomIn}>＋</button>
            </div>

            {/* 视口 */}
            <div className="image-viewport" ref={viewportRef} onScroll={handleScroll}>
                {/* 内容轨道：page 尺寸由 --pagew 变量 + aspect-ratio 驱动，block margin:0 auto 居中 */}
                <div className="pages-track" ref={trackRef}>
                    {pages.map((page) => (
                        <PdfPage
                            key={page.pageNum}
                            page={page}
                            setCanvasRef={setCanvasRef}
                            onRetry={retryPage}
                        />
                    ))}
                </div>
            </div>

            {/* 页脚页码（手机端顶部工具栏隐藏时显示）*/}
            <div className="page-footer">{currentPage + 1} / {total}</div>
        </div>
    )
}
